export const EXCEL_METADATA = 'EXCEL_TO_OBJECT';
export const ORIGINAL_VALUE = 'ORIGINAL_VALUE';
export const CELL_VALUE_TRANSFORMER = 'transformer';
export const COLUMN_NUMBERS = 'COLUMN_NUMBERS';
export const COLUMN_NAMES = 'COLUMN_NAMES';
export const PROP = 'prop';
export const EXCEL_HANDLER_METHOD_PARAM = 'EXCEL_DATA_HANDLER_DECORATOR_PARAMS';