export const EXCEL_METADATA = 'EXCEL_TO_OBJECT';
export const ORIGINAL_VALUE = 'ORIGINAL_VALUE';
export const CELL_VALUE_TRANSFORMER = 'CELL_VALUE_TRANSFORMERS';
export const COLUMN_NUMBERS = 'COLUMN_NUMBERS';
export const COLUMN_NAMES = 'COLUMN_NAMES';